services:
  api:
    build:
      context: .
      dockerfile: Dockerfile
      target: base
    container_name: sysmetrics
    ports:
      - "8000:8000"

  agent:
    build:
      context: .
      dockerfile: Dockerfile
      target: agent
    container_name: agent
    environment:
      - SYS_METRICS_URL=http://api:8000/metrics
    depends_on:
      - api
