name: Pipeline deployement application python

on: 
  push:
    branches: ["main"]

  pull_request:
    branches: ["main"]


jobs:
  
    test-code:
      runs-on: ubuntu-latest

      steps:
        - name: Checout code
          uses: actions/checkout@v6

        - name: Setup python
          uses: actions/setup-python@v7
          with:
            python-version: '3.13' 

        - name: Installer les dépendances
          run:  pip install -r requirements.txt

        - name: Exécuter les tests
          run: pytest -q 